export const carinfo = [
  {
    id: 0,
    title: "Model S",
    description: "Order Online for Touchless Delivery",
    image: "model-s.jpg",
    range: "390",
    time: "1.99",
    topSpeed: "200",
    peakPower: "1,020",
    leftButton: "Custom order",
    rightButton: "Existing inventory",
  },
  {
    id: 1,
    title: "Model 3",
    description: "Order Online for Touchless Delivery",
    image: "model-3.jpg",
    range: "400",
    time: "2.99",
    topSpeed: "180",
    peakPower: "900",
    leftButton: "Custom order",
    rightButton: "Existing inventory",
  },
  {
    id: 2,
    title: "Model X",
    description: "Order Online for Touchless Delivery",
    image: "model-x.jpg",
    range: "350",
    time: "1.55",
    topSpeed: "150",
    peakPower: "1,130",
    leftButton: "Custom order",
    rightButton: "Existing inventory",
  },
  {
    id: 3,
    title: "Model Y",
    description: "Order Online for Touchless Delivery",
    image: "model-y.jpg",
    range: "410",
    time: "2.05",
    topSpeed: "190",
    peakPower: "1,040",
    leftButton: "Custom order",
    rightButton: "Existing inventory",
  },
  {
    id: 4,
    title: "Lowest Cost Solar Panel in America",
    description: "Money-back guarantee",
    image: "solar-panel.jpg",
    leftButton: "Order now",
    rightButton: "Know more",
  },
  {
    id: 5,
    title: "Solar for new roof",
    description: "Solar Roof Costs Less Than a New Roof Plus Solar Panel",
    image: "solar-roof.jpg",
    leftButton: "Order now",
    rightButton: "Know more",
  },
  {
    id: 6,
    title: "Accessories",
    description: "Solar Roof Costs Less Than a New Roof Plus Solar Panel",
    image: "accessories.jpg",
    leftButton: "Shop now",
  },
];
